### ISSUE TITLE
Stuck in loading game

### ISSUE THREAD

**Issue by cooroon** [Avenshy/majsoul_mod_plus#22]
Hi Boss, first of all, thanks a lot for the coding. It works fine and loads home page fine but when I get into actual 3person or 4person game, it does not load past 28%. It always stops there before connecting with other players unless I turn it off. What could be the cause?

**Comment by cooroon** [comment]
It was because I was using Korean translation script. Sorry about that.

**Comment by Avenshy** [comment]
maybe the codes needs to be updated, i will check it tomorrow2022年4月1日 02:02，cooroon ***@***.***>写道：
Hi Boss, first of all, thanks a lot for the coding. I works fine and loads home page fine but when I get into actual 3person or 4person game, it does not load past 28%. It always stops there before connecting with other players unless I turn it off. What could be the cause?
