### ISSUE TITLE
雀魂网址更新为.net后插件失效啦

### ISSUE THREAD

**Issue by kouki-chou** [Avenshy/majsoul_mod_plus#33]
如题，求更新

**Comment by YuXingRen** [comment]
你自己改下应用的网站就完事了

**Comment by MZ1026** [comment]
更改// @match    后的网址为https://game.mahjongsoul.net/

**Comment by kouki-chou** [comment]
> 你自己改下应用的网站就完事了

在哪儿改啊...找了很久没找到啊...求教TOT

**Comment by kouki-chou** [comment]
> 更改// @match 后的网址为https://game.mahjongsoul.net/

没找到在哪儿啊...大胸弟...TOT

**Comment by kouki-chou** [comment]
> 更改// @match 后的网址为https://game.mahjongsoul.net/

我擦，我用的是Header Editor，我是不是问错地方了...

**Comment by Avenshy** [comment]
已更新，安装最新版本即可  

> > 更改// @match 后的网址为https://game.mahjongsoul.net/
> 
> 我擦，我用的是Header Editor，我是不是问错地方了...

和这玩意和没关系啊…
