### ISSUE TITLE
请教一下代码

### ISSUE THREAD

**Issue by thougr** [Avenshy/majsoul_mod_plus#65]
本人前端小白，想问问像uiscript、view.DesktopMgr是怎么找到具体含义的，在code.js也只是看到一两个关键字，而且编译之后看不懂，雀魂油猴好像基本都用这几个，怎么找到雀魂所有这些相关数据的，提前感谢作者

**Comment by Avenshy** [comment]
以前的代码没有混淆，基本和前端开源一样，关键代码都很明显，一目了然

现在代码被混淆了，需要把代码还原后再读。

也可以参照以前版本的代码，大框架没有变过的。

**Comment by thougr** [comment]
明白了，十分感谢

> 以前的代码没有混淆，基本和前端开源一样，关键代码都很明显，一目了然
> 
> 现在代码被混淆了，需要把代码还原后再读。
> 
> 也可以参照以前版本的代码，大框架没有变过的。
