### ISSUE TITLE
0.10.281 BUG

### ISSUE THREAD

**Issue by EntID911** [Avenshy/majsoul_mod_plus#94]
刷新web后装扮消失，回退到0.10.270恢复
角色在对局结束后切换到婚皮
202311/15更新：角色立绘的人物比例出现异常
如：
![IMG_20231115_185036.jpg](https://github.com/Avenshy/majsoul_mod_plus/assets/113762774/24387b68-3302-4476-9c2f-3dc89e099368)
以上比例错误发生在开始对局前玩家角色立绘，碰杠吃，和牌特效

望辛苦修复

**Comment by Avenshy** [comment]
请更新至最新版本

---

> 角色在对局结束后切换到婚皮

老问题了

**Comment by EntID911** [comment]
> 请更新至最新版本
> 
> ---
> 
> > 角色在对局结束后切换到婚皮
> 
> 老问题了

辛苦了❤️
