### ISSUE TITLE
what is safe_code.js?

### ISSUE THREAD

**Issue by daycheat** [Avenshy/majsoul_mod_plus#95]
sorry for posting it on issues, i couldn't find discussions here

if possible, can you explain what has been modified? safe_code.js vs code.js
i'm making bot for majsoul, and i'm wondering if there's any check on the clientside.

**Comment by Avenshy** [comment]
code.js会检测是否使用userscript -> 上报服务器 -> 封禁账号

safe_code.js删除了这部分的代码，但仍然会导致封禁账号
