### ISSUE TITLE
0.10.300

### ISSUE THREAD

**Issue by EntID911** [Avenshy/majsoul_mod_plus#96]
二进宫
吃碰杠的好了
这两个地方依然立绘错误拉伸
![IMG_20231116_135158.jpg](https://github.com/Avenshy/majsoul_mod_plus/assets/113762774/42b496ee-e8b2-4a49-953d-bb328fc6804a)
**↓**没截到图，随便找了一个图当素材，另外荣和特效还有大黑边
![IMG_20231116_134353.jpg](https://github.com/Avenshy/majsoul_mod_plus/assets/113762774/28dbe12a-3b16-4b67-bb1a-f35142f89bb5)

大佬再次辛苦❤️

**Comment by lonci3332** [comment]
我玩游戏时没有更新更新后出现在 F12 中的脚本，结果就出现了这种情况，这危险吗？

**Comment by EntID911** [comment]
> 我玩游戏时没有更新更新后出现在 F12 中的脚本，结果就出现了这种情况，这危险吗？

这只是0.10.300及其之前的版本对对于雀魂新版本的脚本bug，跟危险与否无关，但如果在Commits中看到了关于safe_code.js的更新，那么就尽快更新吧，这点是关乎于安全性的
